name: momentum
description: A super powerful flutter state management library inspired with MVC pattern with a very flexible dependency injection.
version: 1.1.6
homepage: https://github.com/xamantra/momentum

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7
dev_dependencies:
#  pedantic: ^1.8.0
#  test: ^1.6.0
  effective_dart: ^1.2.1